FROM golang:1.23-alpine AS builder
RUN apk add --no-cache git make build-base libpcap-dev
WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN go build ./cmd/assembler


FROM python:3.13-alpine
RUN apk add --no-cache build-base libpcap-dev bsd-compat-headers openssl-dev
WORKDIR /app

COPY ./converters/helpers/requirements.txt ./converters/helpers/requirements.txt
RUN python3 -m pip install -r ./converters/helpers/requirements.txt

COPY --from=builder /build/assembler ./
CMD ["./assembler"]