FROM python:3.14-alpine

RUN apk add --no-cache git build-base

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN BUILD_LIB=1 pip install --no-cache-dir -r requirements.txt

COPY . /app

STOPSIGNAL SIGINT

CMD ["gunicorn", "-w", "3", "-t", "60", "--log-level", "debug", "--capture-output", "--enable-stdio-inheritance", "-b", "0.0.0.0:5000", "webservice:create_app()"]
